apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: app-name
      type: string
      default: myapp
    - name: build-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/myproject/myapp:latest
  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: url
          value: https://github.com/yascodestoday/ci-cd-final-project.git
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: output

    - name: flake8-lint
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: nose-tests
      taskRef:
        name: nose
      runAfter:
        - flake8-lint
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - nose-tests
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
